/**
 * Model identifier glossary — thesis variable names that appear in the
 * site's inline code spans get <abbr> tooltips from this dictionary
 * (matched case-insensitively, so `KJTRE` and `kjtre` both resolve).
 * Prose text is NOT scanned: names like `card` or `delta` collide with
 * English words, so backticks are the signal that a token is code.
 *
 * Naming scheme (thesis, Appendix A): first letter is the quantity —
 * w flow, h enthalpy, r density, t temperature, p pressure, q heat rate,
 * n shaft speed, c control signal, k constant (second letter then gives
 * the constant's kind: kj inertia, kv volume, kf friction, ku heat
 * transfer, kc controller gain, ktc time constant) — and the tail names
 * the component (tre turbine-generator, fp feed pump, drs drum steam...).
 */
export const identifiers: Record<string, string> = {
  // rotor inertias (kj*)
  kjtre: 'constant: rotational inertia J of the TuRbine-gEnerator rotor (slug·ft²; the corrected WR²/g_c value)',
  kjfpe: 'constant: rotational inertia J of the Feed Pump (Effective, incl. its drive turbine)',
  kjcp: 'constant: rotational inertia J of the Condensate Pump rotor',
  kjrp: 'constant: rotational inertia J of the Recirculation Pump rotor',
  kjfd: 'constant: rotational inertia J of a Forced-Draft fan rotor',
  kjid: 'constant: rotational inertia J of an Induced-Draft fan rotor',
  // shaft speeds (n*)
  ntr: 'state 16: TuRbine-generator shaft speed (rad/s)',
  nfp: 'state 1: Feed Pump turbine shaft speed (rad/s)',
  nrp: 'state 6: Recirculation Pump speed (rad/s)',
  ncp: 'state 17: Condensate Pump speed (rad/s)',
  nfd: 'state 21: Forced-Draft fan speed (rad/s)',
  nid: 'state 22: Induced-Draft fan speed (rad/s)',
  nelec: 'grid input: synchronous speed from grid frequency (376.991 rad/s at 60 Hz)',
  velec: 'grid input: line voltage (4160 V nominal)',
  delta: 'state 47: generator power angle (rad)',
  ldc: 'scenario input: Load Demand Computer signal (1–5 V; 5 = 100% load)',
  // flows (w*)
  wfl: 'flow: FueL to the burners (lbm/s)',
  war: 'flow: combustion AiR (lbm/s)',
  wgr: 'flow: recirculated flue Gas (lbm/s)',
  wwwg: 'flow: total furnace/WaterWall Gas = war + wfl + wgr (lbm/s)',
  whp: 'flow: steam through the HP turbine (lbm/s)',
  wtv: 'flow: steam through the Throttle/governor Valves (lbm/s)',
  wfw: 'flow: FeedWater to the drum (lbm/s)',
  wrw: 'flow: Recirculated Water through the waterwalls (lbm/s)',
  wdrs: 'flow: DRum Steam leaving to the superheaters (lbm/s)',
  wsy: 'flow: superheat SpraY water (lbm/s)',
  wry: 'flow: Reheat spraY water (lbm/s)',
  wft: 'flow: extraction steam to the Feed pump Turbine (lbm/s)',
  wcw: 'flow: Condensate Water (lbm/s)',
  wdrbd: 'flow: DRum BlowDown (lbm/s)',
  wrh1: 'flow: into the ReHeater = HP exhaust + reheat spray (lbm/s)',
  wiv: 'flow: through the Intercept Valve into the IP turbine (lbm/s)',
  whpo: 'flow: HP turbine Outlet after extractions (lbm/s)',
  wipo: 'flow: IP turbine Outlet after extractions (lbm/s)',
  wip: 'flow: steam through the IP turbine (lbm/s)',
  wlp: 'flow: steam through the LP turbine (lbm/s)',
  wgo: 'flow: flue Gas Out to the stack (lbm/s)',
  wfd: 'flow: air through the Forced-Draft fans (lbm/s)',
  wid: 'flow: gas through the Induced-Draft fans (lbm/s)',
  // enthalpies (h*)
  hsso: 'state 11: Secondary Superheater Outlet enthalpy = main steam (Btu/lbm)',
  hpso: 'state 9: Primary Superheater Outlet enthalpy (Btu/lbm)',
  hrho: 'state 14: ReHeater Outlet enthalpy (Btu/lbm)',
  hrh1: 'signal: cold reheat enthalpy = HP exhaust into the reheater (Btu/lbm)',
  hcro: 'signal: CRoss-Over pipe enthalpy = IP exhaust (Btu/lbm)',
  hlpo: 'signal: LP turbine exhaust enthalpy (Btu/lbm)',
  hhho: 'state 2: HP feedwater Heater Outlet enthalpy (Btu/lbm)',
  hlho: 'state 18: LP feedwater Heater Outlet enthalpy (Btu/lbm)',
  heco: 'state 3: ECOnomizer outlet feedwater enthalpy (Btu/lbm)',
  // densities and vessel states (r*, v*)
  rdrs: 'state 5: DRum Steam density (lbm/ft³)',
  rdrw: 'signal: DRum Water density, saturated (lbm/ft³)',
  vdrw: 'state 4: Drum Water volume (ft³)',
  vdew: 'state 19: DEaerator Water volume (ft³)',
  rdes: 'state 20: DEaerator Steam density (lbm/ft³)',
  rsso: 'state 10: Secondary Superheater Outlet steam density (lbm/ft³)',
  rrho: 'state 13: ReHeater Outlet steam density (lbm/ft³)',
  rcro: 'state 15: CRoss-Over pipe steam density (lbm/ft³)',
  // temperatures (t*)
  twwm: 'state 7: WaterWall Metal temperature (°R)',
  trho: 'signal: ReHeater Outlet steam temperature (°R)',
  tsso: 'signal: Secondary Superheater Outlet (main steam) temperature (°R)',
  tfn1: 'signal: FurNace exit gas temperature (°R)',
  twwge: 'signal: effective WaterWall Gas (flame) temperature for radiation (°R)',
  tecgo: 'signal: ECvonomizer Gas Outlet (stack-side) temperature (°R)',
  tgr: 'signal: recirculated Gas temperature (°R)',
  tdrs: 'signal: DRum Saturation temperature (°R)',
  tapao: 'constant-derived: Air Preheater Air Outlet temperature (948 °R)',
  // pressures (p*)
  psso: 'signal: throttle pressure at the Secondary Superheater Outlet (psia)',
  pdrs: 'signal: DRum Steam pressure (psia)',
  prho: 'signal: ReHeater Outlet pressure (psia)',
  p1st: 'signal: turbine 1ST-stage pressure — the internal steam-flow meter (psia)',
  pfvd: 'signal: Feedwater Valve Differential pressure (psi)',
  pfn: 'signal: FurNace pressure (psia)',
  psco: 'signal: Steam Chest pressure at the governing stage (psia)',
  pcro: 'signal: CRoss-Over pipe pressure (psia)',
  pcn: 'signal: CoNdenser pressure (psia)',
  mrhe: 'signal: ReHeater Effective mass — steam + lumped metal (lbm)',
  msse: 'signal: Secondary Superheater Effective mass (lbm)',
  mpse: 'signal: Primary Superheater Effective mass (lbm)',
  mece: 'signal: EConomizer Effective mass (lbm)',
  // heat rates (q*)
  qwwgm: 'heat rate: furnace Gas to WaterWall Metal, radiant (Btu/s)',
  qwwmw: 'heat rate: WaterWall Metal to boiling Water (Btu/s)',
  qps: 'heat rate: gas to Primary Superheater steam (Btu/s)',
  qss: 'heat rate: gas to Secondary Superheater steam (Btu/s)',
  qrh: 'heat rate: gas to ReHeater steam (Btu/s)',
  qec: 'heat rate: gas to EConomizer feedwater (Btu/s)',
  // powers (mw*)
  mwtro: 'signal: total TuRbine mechanical power Output (ft·lbf/s internally)',
  mwgn: 'signal: GeNerator electrical power drawn by the grid',
  mwhp: 'signal: HP cylinder mechanical power',
  mwip: 'signal: IP cylinder mechanical power',
  mwlp: 'signal: LP cylinder mechanical power',
  mwo: 'signal: net electrical power output (for display/logging)',
  // levels
  xdrw: 'signal: DRum Water level (in, ±15 range)',
  xdew: 'signal: DEaerator Water level (in)',
  // control signals (c*) — demands the plant sees
  cfld: 'state 36: FueL Demand signal (1–5 V → 0–90 lbm/s)',
  card: 'state 35: AiR Demand signal (1–5 V → FD fan vanes)',
  cgrd: 'state 38: Gas Recirculation Demand signal (1–5 V → 0–500 lbm/s)',
  cfnd: 'state 37: FurNace-pressure Demand signal (1–5 V → ID fan vanes)',
  cxggd: 'state 42: burner tilt (X-GG) Demand signal (1–5 V → ±30°)',
  csyd: 'state 43: superheat SpraY Demand signal (1–5 V)',
  cfwd: 'state 40: FeedWater valve Demand signal (1–5 V)',
  cdwd: 'state 41: Deaerator (condensate) valve Demand signal (1–5 V)',
  cftd: 'state 39: Feed pump Turbine steam Demand signal (1–5 V)',
  cacvd: 'state 46: governor Control-Valve Demand signal (1–5 V)',
  c3md: 'state 23: boiler-Master Demand integrator (winds up when pressure set point unreachable)',
  c2gr: 'state 27: Gas-Recirculation integrator (frozen inside the tilt deadband)',
  // actuator areas (a*)
  acv: 'area: governor Control Valves (0–1, from cacvd)',
  afv: 'area: Feedwater Valve (0–1, from cfwd)',
  avf: 'area: FD fan inlet Vanes (0–1, from card)',
  avi: 'area: ID fan inlet Vanes (0–1, from cfnd)',
  adv: 'area: Deaerator (condensate) Valve (0–1, from cdwd)',
  xgg: 'signal: burner tilt angle (rad, ±0.5236 = ±30°)',
  // key constants met in prose
  kfcal: 'constant: Fan-curve CALibration (×1.10 on the fan ΔP coefficients in airGas; pinned by the thesis-published steady states)',
  khfl: 'constant: fuel Heating value (18,200 Btu/lbm)',
  kafr: 'constant: Air/Fuel Ratio demand (13.65 lbm air per lbm fuel)',
  ktrh: 'scheduled set point: ReHeat outlet temperature (°R, from whp)',
  ktss: 'scheduled set point: main (Secondary Superheater) steam temperature (°R, from whp)',
  knp087: 'constant: 0.08727 rad = 5° — the gas-recirc tilt deadband half-width',
  kcv: 'constant: governor Control Valve flow coefficient',
  kvrh: 'constant: ReHeater fill Volume (ft³)',
  kvdr: 'constant: DRum total Volume (1958.7 ft³)',
  kswwm: 'constant: Specific heat of WaterWall Metal (0.11 Btu/lbm·°R)',
  kuwwmw: 'constant: boiling heat-transfer coefficient, WaterWall Metal to Water (cube law)',
  kuwwgm: 'constant: radiant heat-transfer coefficient, Gas to WaterWall Metal (T⁴ law)',
  uxgg: 'signal: tilt correction factor on radiant absorption (1 − 0.2865·tan xgg)',
  ungg: 'signal: gun-count correction factor on radiant absorption',
  uwwgm: 'signal: effective radiant coefficient = kuwwgm·uxgg·ungg',
};
